# Generated by Django 5.1.3 on 2024-11-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channel_location'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total project cost', max_digits=10, verbose_name='Cost')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost for this channel', max_digits=10, verbose_name='Cost')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_channels', to='channels.channel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_channels', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Channel',
                'verbose_name_plural': 'Project Channels',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='channels',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectChannel', to='channels.channel', verbose_name='Advertising Channels'),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONTRACT', 'Contract'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type')),
                ('file', models.FileField(upload_to='projects/documents/', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Step',
                'verbose_name_plural': 'Project Steps',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
