[project]
name = "ad-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-vite>=3.0.5",
    "django>=5.1.3",
    "djangorestframework>=3.15.2",
    "markdown>=3.7",
    "python-dotenv>=1.0.1",
]
