# Generated by Django 5.1.3 on 2024-11-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Channel Type',
                'verbose_name_plural': 'Channel Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved'), ('IN_USE', 'In Use'), ('BLOCKED', 'Blocked')], default='FREE', max_length=20, verbose_name='Status')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('technical_specs', models.TextField(blank=True, verbose_name='Technical Specifications')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='channels.channeltype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['-created_at'],
            },
        ),
    ]
