# Generated by Django 5.1.3 on 2024-11-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
    ]
